services:
  queue-svc:
    container_name: queue-svc
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '5015:5015'
    restart: always
    env_file:
      - ../.env.production
    command: [ 'uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '5015', '--workers', '4' ]
