services:
  queue-svc:
    container_name: queue-svc
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5015:5015"
    restart: always
    depends_on:
      - queue-svc-postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@queue-svc-postgres:5432/queue_db
      ENVIRONMENT: local
    command: [ 'uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '5015' ]

  queue-svc-postgres:
    container_name: queue-svc-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: queue_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
